### ISSUE TITLE
Should we set a default layout?

### ISSUE THREAD

**Issue by gabriel** [YOLayout/YOLayout#20]
It would be cool to have a default layout set for views with only a single view, and for multiple views, laid out vertically.

If `subviews.count == 1`:
```objc
self.layout = [YOLayout layoutWithLayoutBlock:^(id<YOLayout> layout, CGSize size) {
  [layout setFrame:CGRectMake(0, 0, size.width, size.height) view:view];
  return size;  
}];
```

If `subviews.count > 1`:
```objc
self.layout = [YOLayout layoutWithLayoutBlock:^(id<YOLayout> layout, CGSize size) {
  CGFloat y = 0;
  for (id subview in view.subviews) {
    y += [layout sizeToFitVerticallyInFrame:(0, y, size.width, 0) view:subview].size.height;
  }
  return CGSizeMake(size.width, y);
}];
```

Maybe even allow insets.

We could also define these blocks and allow people to use them (manually):

```objc
self.layout = [YOLayout layoutWithLayoutBlock:YOLayoutVerticalBlock(insets)];
```

**Comment by gabriel** [comment]
After thinking about it, I don't like automatic, but I like pre-defined blocks that are easy to use/set.

**Comment by johnboiles** [comment]
I agree. I don't like automatic, but I'd certainly open to having some pre-defined blocks. I wonder how much I'd use them in practice.
