### ISSUE TITLE
Main import should be #import <YOLayout/YOLayout.h> for YOLayout framework

### ISSUE THREAD

**Issue by gabriel** [YOLayout/YOLayout#3]
But its hard to do this since YOLayout contains "real stuff".

**Comment by johnboiles** [comment]
Yeah, that's hard. `[YOLayoutController layoutWithLayoutBlock...` doesn't have the same ring to it

**Comment by johnboiles** [comment]
Could always rename the `YOLayout` class to `YOLO` :)

    self.layout = [YOLO layoutWithLayoutBlock:...

**Comment by gabriel** [comment]
tehnically I don't think YOLayout.h/m has to have YOLayout defined... we
could make

YOLayout.h

#import "YOLayout_IMP.h"

and YOYOLayout defines YOLayout

Its weird but not as weird as #import <YOLayout/YOView.h>?

**Comment by johnboiles** [comment]
That makes sense to me! A little weird, but I can't think of a better way to do it.
