### ISSUE TITLE
We should cleanup YOLayout methods.

### ISSUE THREAD

**Issue by gabriel** [YOLayout/YOLayout#9]
Lots of methods I'm not sure if we need them or what they really do?

We could nuke:
`- (CGRect)setFrame:(CGRect)frame view:(id)view needsLayout:(BOOL)needsLayout;`

What do these really do? I forget:
`- (CGRect)setFrameInRect:(CGRect)inRect view:(id)view;`
`- (CGRect)setX:(CGFloat)x frame:(CGRect)frame view:(id)view;` (Why not user setOrigin?)
`- (CGRect)setY:(CGFloat)y frame:(CGRect)frame view:(id)view;` (Why not user setOrigin?)

And some deprecated ones.

We should do some examples/documentation for:

`- (CGRect)setFrame:(CGRect)frame inRect:(CGRect)inRect view:(id)view options:(YOLayoutOptions)options;`

Cause that can be useful sometimes but it's hard to grok.

**Comment by johnboiles** [comment]
Totally agree here.

I also wonder if we could rename `setFrame:inRect:view:` to something that doesn't show up at the top of the autocomplete. I think most of the time you want `setFrame:view:options:` or `setFrame:view:sizeToFit`, not any of the others.
